# base CoMSES Dockerfile
FROM ubuntu:16.04
MAINTAINER CoMSES Net <dev@comses.net>
USER root
ONBUILD ENV COMSES_UID=2718
ONBUILD ENV COMSES_USER=comses
ONBUILD RUN useradd -m --uid $COMSES_UID $COMSES_USER
